Repository ss14-ganimed/ENT14-Master, pull requests merged in 2023-08, with the labels that each got.

#15 Поименная локализация
  Content.Shared/Humanoid/NamingSystem.cs
  Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
  Content.Shared/Preferences/HumanoidCharacterProfile.cs
  Resources/Locale/ru-RU/species/species.ftl
  Resources/Prototypes/Datasets/Names/arachnid_first.yml
  Resources/Prototypes/Datasets/Names/arachnid_last.yml
  Resources/Prototypes/Datasets/Names/cargo_shuttle.yml
  Resources/Prototypes/Datasets/Names/clown.yml
  Resources/Prototypes/Datasets/Names/diona.yml
  Resources/Prototypes/Datasets/Names/fake_human_first.yml
  Resources/Prototypes/Datasets/Names/fake_human_last.yml
  Resources/Prototypes/Datasets/Names/first.yml
  Resources/Prototypes/Datasets/Names/first_female.yml
  Resources/Prototypes/Datasets/Names/first_male.yml
  Resources/Prototypes/Datasets/Names/fortunes.yml
  Resources/Prototypes/Datasets/Names/last_female.yml
  Resources/Prototypes/Datasets/Names/last_male.yml
  Resources/Prototypes/Datasets/Names/military.yml
  Resources/Prototypes/Datasets/Names/moth_first_female.yml
  Resources/Prototypes/Datasets/Names/moth_first_male.yml
  Resources/Prototypes/Datasets/Names/moth_last.yml
  Resources/Prototypes/Datasets/Names/ninja.yml
  Resources/Prototypes/Datasets/Names/ninja_title.yml
  Resources/Prototypes/Datasets/Names/regalrat.yml
  Resources/Prototypes/Datasets/Names/reptilian_female.yml
  Resources/Prototypes/Datasets/Names/reptilian_male.yml
  Resources/Prototypes/Datasets/Names/revenant.yml
  Resources/Prototypes/Datasets/Names/skeleton_first.yml
  Resources/Prototypes/Datasets/Names/syndicate.yml
  Resources/Prototypes/Datasets/Names/wizard_first.yml
  Resources/Prototypes/Datasets/Names/wizard_last.yml
  Resources/Prototypes/Datasets/adjectives.yml
  Resources/Prototypes/Datasets/tips.yml
  Resources/Prototypes/Datasets/verbs.yml
  Resources/Prototypes/Entities/Mobs/Species/moth.yml
  Resources/Prototypes/Species/arachnid.yml
  Resources/Prototypes/Species/moth.yml
  Resources/Prototypes/Voice/disease_emotes.yml
  Resources/Prototypes/Voice/speech_emotes.yml
  Resources/Prototypes/Voice/speech_sounds.yml
  Resources/Prototypes/radio_channels.yml
  Tools/ss14_ru/__init__.py
  Tools/ss14_ru/file.py
  Tools/ss14_ru/fluentast.py
  Tools/ss14_ru/fluentastcomparer.py
  Tools/ss14_ru/fluentastmanager.py
  Tools/ss14_ru/fluentformatter.py
  Tools/ss14_ru/keyfinder.py
  Tools/ss14_ru/lokalise_fluent_ast_comparer_manager.py
  Tools/ss14_ru/lokalise_project.py
  Tools/ss14_ru/lokalisemodels.py
  Tools/ss14_ru/project.py
  Tools/ss14_ru/requirements.txt
  Tools/ss14_ru/translationsassembler.py
  Tools/ss14_ru/yamlextractor.py
  Tools/ss14_ru/yamlmodels.py
Labels: C#, Изменено: Переводы, Приоритет: 1 - Неотложный, Размер: Средний

#17 Мойдодыр ебучий
  Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
Labels: Приоритет: 2 - Высокий, Размер: Малый, Тип: Баланс

#22 Небольшие изменения датасета мотыльков
  Resources/Prototypes/Datasets/Names/moth_first_female.yml
  Resources/Prototypes/Datasets/Names/moth_first_male.yml
  Resources/Prototypes/Datasets/Names/moth_last.yml
Labels: Изменено: Переводы, Приоритет: 4 - Низкий, Размер: Малый

#20 Квартирмейстер лишён статуса командования
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Textures/Interface/Misc/job_icons.rsi/QuarterMaster.png
Labels: Изменено: Спрайты, Приоритет: 2 - Высокий, Размер: Малый, Тип: Рефакторинг

#24 Взлом консоли запуска ротационного шаттла
  Content.Server/Shuttles/Systems/EmergencyShuttleSystem.Console.cs
Labels: C#, Приоритет: 3 - Средний, Тип: Рефакторинг

#25 Реализация возможности пополнения вендоматов
  Content.Server/VendingMachines/VendingMachineSystem.cs
  Content.Shared/VendingMachines/VendingMachineComponent.cs
  Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
Labels: C#, Приоритет: 4 - Низкий, Размер: Малый

#29 Head's can be antag
  Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
Labels: Приоритет: 2 - Высокий, Размер: Малый, Тип: Рефакторинг

#33 Указ директоров НТ о смене обозначений должности.
  Resources/Locale/ru-RU/job/job-names.ftl
Labels: Изменено: Переводы, Приоритет: 2 - Высокий

#37 Консоль криминальных записей
  Content.Client/CriminalRecords/GeneralCriminalRecordsConsoleBoundUserInterface.cs
  Content.Client/CriminalRecords/GeneralCriminalRecordsConsoleWindow.xaml
  Content.Client/CriminalRecords/GeneralCriminalRecordsConsoleWindow.xaml.cs
  Content.Server/CriminalRecords/Components/GeneralCriminalRecordsConsoleComponent.cs
  Content.Server/CriminalRecords/GeneralCriminalRecordsConsoleSystem.cs
  Content.Server/CriminalRecords/Systems/CriminalRecordsSystem.cs
  Content.Shared/CriminalRecords/GeneralCriminalRecord.cs
  Content.Shared/CriminalRecords/SharedGeneralCriminalRecordConsoleSystem.cs
  Content.Shared/Security/SecurityStatus.cs
  Content.Shared/StationRecords/GeneralStationRecord.cs
  Resources/Locale/en-US/criminal-records/general-criminal-records.ftl
  Resources/Locale/en-US/research/technologies.ftl
  Resources/Locale/ru-RU/criminal-records/general-criminal-records.ftl
  Resources/Locale/ru-RU/research/technologies.ftl
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/electronics.yml
  Resources/Prototypes/Research/arsenal.yml
Labels: C#, Изменено: UI, Изменено: Переводы, Приоритет: 3 - Средний, Размер: Средний

#38 Замена бега на ходьбу
  Content.Shared/Movement/Components/InputMoverComponent.cs
  runall.bat
Labels: C#, Приоритет: 4 - Низкий, Размер: Малый

#49 Playtime
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/senior_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Medical/senior_physician.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Science/senior_researcher.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/psychologist.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
Labels: Приоритет: 2 - Высокий, Размер: Малый

#50 Справочник по уровням угрозы
  Resources/Locale/ru-RU/guidebook/ganimed/guides.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/ganimed/entities/objects/misc/books.ftl
  Resources/Prototypes/Entities/Ganimed/Objects/Misc/books.yml
  Resources/Prototypes/Guidebook/Ganimed/AlertCode.yml
  Resources/Prototypes/Guidebook/ss14.yml
  Resources/ServerInfo/Guidebook/Ganimed/AlertCodes/AlertCode.xml
  Resources/ServerInfo/Guidebook/Ganimed/AlertCodes/CentCommAlerts.xml
  Resources/ServerInfo/Guidebook/Ganimed/AlertCodes/CommonAlerts.xml
  Resources/ServerInfo/Guidebook/Ganimed/AlertCodes/SpecificAlerts.xml
Labels: Изменено: UI, Изменено: Переводы, Приоритет: 3 - Средний, Размер: Малый
