Repository ss14-ganimed/ENT14-Master, pull requests merged in 2024-03, with the labels that each got.

#98 Word replace remove
  Resources/Locale/ru-RU/corvax/speech/speech-chatsan.ftl
  Resources/Prototypes/Accents/word_replacements.yml
Labels: Изменено: Переводы, Приоритет: 3 - Средний, Размер: Малый

#100 Небольшая переработка анонсов
  Resources/Audio/Announcements/announce.ogg
  Resources/Audio/Announcements/infestation.ogg
  Resources/Audio/Announcements/power_off.ogg
  Resources/Audio/Announcements/power_on.ogg
  Resources/Locale/ru-RU/station-events/events/mouse-migration.ftl
  Resources/Prototypes/GameRules/events.yml
Labels: Изменено: Звуки, Приоритет: 3 - Средний, Размер: Малый

#99 Респрайт водолазки НРа
  Resources/Textures/Clothing/Uniforms/Jumpskirt/rnd.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/rnd.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/rnd.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/rnd.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/rnd.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/rnd.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/rnd.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/rnd.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/rnd.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/rnd.rsi/meta.json
Labels: Изменено: Спрайты, Приоритет: 3 - Средний, Размер: Малый, Статус: Ожидает изменений

#101 Подушка с Бориславой
  Resources/Locale/ru-RU/ss14-ru/prototypes/ganimed/entities/objects/misc/pillows.ftl
  Resources/Prototypes/Ganimed/Entities/Markers/Spawners/Random/pillows.yml
  Resources/Prototypes/Ganimed/Entities/Objects/Misc/pillows.yml
  Resources/Textures/Ganimed/Objects/pillows.rsi/icon-six-inhand-left.png
  Resources/Textures/Ganimed/Objects/pillows.rsi/icon-six-inhand-right.png
  Resources/Textures/Ganimed/Objects/pillows.rsi/icon-six.png
  Resources/Textures/Ganimed/Objects/pillows.rsi/meta.json
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 3 - Средний, Размер: Малый

#102 Фикс цели РНД
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
Labels: Изменено: Переводы, Приоритет: 3 - Средний, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Баланс, Сложность: 0-3 (Низкая)

#104 Улучшение эмоция.ogg
  Resources/Audio/Voice/Human/female_cough_1.ogg
  Resources/Audio/Voice/Human/female_cough_2.ogg
  Resources/Audio/Voice/Human/femalescream_1.ogg
  Resources/Audio/Voice/Human/femalescream_2.ogg
  Resources/Audio/Voice/Human/femalescream_3.ogg
  Resources/Audio/Voice/Human/femalescream_4.ogg
  Resources/Audio/Voice/Human/femalescream_5.ogg
  Resources/Audio/Voice/Human/femalescream_6.ogg
  Resources/Audio/Voice/Human/laugh_female-1.ogg
  Resources/Audio/Voice/Human/laugh_female-2.ogg
  Resources/Audio/Voice/Human/laugh_female-3.ogg
  Resources/Audio/Voice/Human/laugh_female-4.ogg
  Resources/Audio/Voice/Human/laugh_female-5.ogg
  Resources/Audio/Voice/Human/laugh_female-6.ogg
  Resources/Audio/Voice/Human/laugh_female-7.ogg
  Resources/Audio/Voice/Human/laugh_female-8.ogg
  Resources/Audio/Voice/Human/laugh_female-9.ogg
  Resources/Audio/Voice/Human/laugh_male-1.ogg
  Resources/Audio/Voice/Human/laugh_male-2.ogg
  Resources/Audio/Voice/Human/laugh_male-3.ogg
  Resources/Audio/Voice/Human/laugh_male-4.ogg
  Resources/Audio/Voice/Human/laugh_male-5.ogg
  Resources/Audio/Voice/Human/laugh_male-6.ogg
  Resources/Audio/Voice/Human/laugh_male-7.ogg
  Resources/Audio/Voice/Human/laugh_male-8.ogg
  Resources/Audio/Voice/Human/laugh_male-9.ogg
  Resources/Audio/Voice/Human/male_cough_1.ogg
  Resources/Audio/Voice/Human/male_cough_2.ogg
  Resources/Audio/Voice/Human/malescream_1.ogg
  Resources/Audio/Voice/Human/malescream_2.ogg
  Resources/Audio/Voice/Human/malescream_3.ogg
  Resources/Audio/Voice/Human/malescream_4.ogg
  Resources/Audio/Voice/Human/malescream_5.ogg
  Resources/Audio/Voice/Human/malescream_6.ogg
  Resources/Audio/Voice/Human/manlaugh1.ogg
  Resources/Audio/Voice/Human/manlaugh2.ogg
  Resources/Audio/Voice/Human/womanlaugh.ogg
  Resources/Prototypes/SoundCollections/emotes.yml
  Resources/Prototypes/SoundCollections/screams.yml
  Resources/Prototypes/Voice/speech_emote_sounds.yml
Labels: Изменено: Звуки, Приоритет: 3 - Средний, Размер: Малый

#105 Респрайт скафандра СИ от маппера
  Resources/Textures/Clothing/Head/Hardsuits/engineering-white.rsi/icon-flash.png
  Resources/Textures/Clothing/Head/Hardsuits/engineering-white.rsi/icon.png
  Resources/Textures/Clothing/Head/Hardsuits/engineering-white.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/engineering-white.rsi/off-equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hardsuits/engineering-white.rsi/off-inhand-left.png
  Resources/Textures/Clothing/Head/Hardsuits/engineering-white.rsi/off-inhand-right.png
  Resources/Textures/Clothing/Head/Hardsuits/engineering-white.rsi/on-equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hardsuits/engineering-white.rsi/on-inhand-left.png
  Resources/Textures/Clothing/Head/Hardsuits/engineering-white.rsi/on-inhand-right.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/engineering-white.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/engineering-white.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/engineering-white.rsi/inhand-left.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/engineering-white.rsi/inhand-right.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/engineering-white.rsi/meta.json
Labels: Изменено: Спрайты, Приоритет: 4 - Низкий, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Предложение

#106 Респрайт халата РД
  Resources/Textures/Clothing/OuterClothing/Coats/rd_coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Coats/rd_coat.rsi/icon-open.png
  Resources/Textures/Clothing/OuterClothing/Coats/rd_coat.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Coats/rd_coat.rsi/meta.json
  Resources/Textures/Clothing/OuterClothing/Coats/rd_coat.rsi/open-equipped-OUTERCLOTHING.png
Labels: Изменено: Спрайты, Приоритет: 4 - Низкий, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Предложение

#107 Спрайты кисс теперь наши, а не общие
  Resources/Textures/Ganimed/Clothing/Hands/paws.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Neck/Cloaks/hieroglyphics.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Neck/Cloaks/orange.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Shoes/unati.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Uniforms/bridgeofficer.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Uniforms/military.rsi/meta.json
  Resources/Textures/Ganimed/Mobs/Customization/fox_parts.rsi/meta.json
  Resources/Textures/Ganimed/Objects/Tools/paperlantern.rsi/meta.json
  Resources/Textures/Ganimed/Objects/Tools/paperlantern2.rsi/meta.json
  Resources/Textures/Ganimed/Objects/pillows.rsi/meta.json
Labels: Приоритет: 2 - Высокий, Размер: Малый, Статус: Нуждается в рассмотрении

#108 Офицер мостика
  Resources/Locale/ru-RU/job/job-description.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/jobs.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
  Resources/Prototypes/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/bridge_officer.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/Roles/play_time_trackers.yml
  Resources/Prototypes/StatusEffects/job.yml
  Resources/Textures/Interface/Misc/job_icons.rsi/BridgeOfficer.png
  Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
  Resources/Textures/Objects/Devices/pda.rsi/meta.json
  Resources/Textures/Objects/Devices/pda.rsi/pda-bridgeofficer.png
  Resources/Textures/Objects/Misc/id_cards.rsi/idbridgeofficer.png
  Resources/Textures/Objects/Misc/id_cards.rsi/meta.json
Labels: Изменено: Переводы, Приоритет: 2 - Высокий, Размер: Средний, Статус: Нуждается в рассмотрении

#109 Хотфикс офицера мостика
  Resources/Prototypes/Roles/Jobs/Wildcards/bridge_officer.yml
Labels: Приоритет: 2 - Высокий, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Баланс

#110 Иконки для спец отрядов.
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/StatusEffects/job.yml
  Resources/Textures/Interface/Misc/job_icons.rsi/DeathSquad.png
  Resources/Textures/Interface/Misc/job_icons.rsi/ERTChaplain.png
  Resources/Textures/Interface/Misc/job_icons.rsi/ERTEngineer.png
  Resources/Textures/Interface/Misc/job_icons.rsi/ERTJanitor.png
  Resources/Textures/Interface/Misc/job_icons.rsi/ERTLeader.png
  Resources/Textures/Interface/Misc/job_icons.rsi/ERTMedical.png
  Resources/Textures/Interface/Misc/job_icons.rsi/ERTOfficer.png
  Resources/Textures/Interface/Misc/job_icons.rsi/Nanotrasen.png
  Resources/Textures/Interface/Misc/job_icons.rsi/SRT.png
  Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 3 - Средний, Размер: Малый, Статус: Нуждается в рассмотрении

#111 Очередной фикс офицера мостика
  Resources/Prototypes/Ganimed/Catalog/Loadout/Belt/belts.yml
  Resources/Prototypes/Ganimed/Catalog/Loadout/Eyes/glasses.yml
  Resources/Prototypes/Ganimed/Catalog/Loadout/Eyes/huds.yml
  Resources/Prototypes/Ganimed/Catalog/Loadout/Hands/gloves.yml
  Resources/Prototypes/Ganimed/Catalog/Loadout/Head/berets.yml
  Resources/Prototypes/Ganimed/Catalog/Loadout/Masks/masks.yml
  Resources/Prototypes/Ganimed/Catalog/Loadout/Neck/misc.yml
  Resources/Prototypes/Ganimed/Catalog/Loadout/Shoes/boots.yml
  Resources/Prototypes/Ganimed/Catalog/Loadout/Uniform/uniform.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/bridge_officer.yml
Labels: Приоритет: 2 - Высокий, Размер: Малый, Статус: Нуждается в рассмотрении

#113 Гарнитуры для спец. отрядов
  Resources/Locale/ru-RU/headset/headset-component.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/ears/headsets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/ears/headsets_alt.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/encryption_keys.ftl
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
  Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
  Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
  Resources/Prototypes/radio_channels.yml
  Resources/Textures/Clothing/Ears/Headsets/deathsquad.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/deathsquad.rsi/icon.png
  Resources/Textures/Clothing/Ears/Headsets/deathsquad.rsi/meta.json
  Resources/Textures/Clothing/Ears/Headsets/ert.rsi/alt-equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/ert.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/ert.rsi/icon.png
  Resources/Textures/Clothing/Ears/Headsets/ert.rsi/icon_alt.png
  Resources/Textures/Clothing/Ears/Headsets/ert.rsi/meta.json
  Resources/Textures/Clothing/Ears/Headsets/mtf.rsi/alt-equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/mtf.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/mtf.rsi/icon.png
  Resources/Textures/Clothing/Ears/Headsets/mtf.rsi/icon_alt.png
  Resources/Textures/Clothing/Ears/Headsets/mtf.rsi/meta.json
  Resources/Textures/Clothing/Ears/Headsets/specops.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/specops.rsi/icon.png
  Resources/Textures/Clothing/Ears/Headsets/specops.rsi/meta.json
  Resources/Textures/Clothing/Ears/Headsets/srt.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/srt.rsi/icon.png
  Resources/Textures/Clothing/Ears/Headsets/srt.rsi/meta.json
  Resources/Textures/Objects/Devices/encryption_keys.rsi/crypt_black.png
  Resources/Textures/Objects/Devices/encryption_keys.rsi/deathsquad_label.png
  Resources/Textures/Objects/Devices/encryption_keys.rsi/ert_label.png
  Resources/Textures/Objects/Devices/encryption_keys.rsi/meta.json
  Resources/Textures/Objects/Devices/encryption_keys.rsi/mtf_label.png
  Resources/Textures/Objects/Devices/encryption_keys.rsi/specops_label.png
  Resources/Textures/Objects/Devices/encryption_keys.rsi/srt_label.png
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 2 - Высокий, Размер: Малый

#116 Шприцом и пипеткой теперь можно высасывать лужи
  Resources/Prototypes/Entities/Effects/puddle.yml
Labels: Приоритет: 3 - Средний, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Баланс, Тип: Предложение

#115 Мантия офицера мостика
  Resources/Locale/ru-RU/ganimed/entities/clothing/Mantels.ftl
  Resources/Prototypes/Ganimed/Entities/Clothing/Neck/mantels.yml
  Resources/Prototypes/Recipes/Lathes/clothing.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/bridge_officer.yml
  Resources/Textures/Ganimed/Clothing/Neck/Mantles/BridgeofficerMantle.rsi/equipped-NECK.png
  Resources/Textures/Ganimed/Clothing/Neck/Mantles/BridgeofficerMantle.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Neck/Mantles/BridgeofficerMantle.rsi/meta.json
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 4 - Низкий, Размер: Малый, Статус: Нуждается в рассмотрении

#119 Белая водолазка
  Resources/Locale/ru-RU/ganimed/entities/clothing/Uniform.ftl
  Resources/Prototypes/Ganimed/Catalog/Loadout/Uniform/misc.yml
  Resources/Prototypes/Ganimed/Entities/Clothing/Uniforms/misc.yml
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpskirt/whiteturtleneck.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpskirt/whiteturtleneck.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpskirt/whiteturtleneck.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpskirt/whiteturtleneck.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpskirt/whiteturtleneck.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpsuit/whiteturtleneck.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpsuit/whiteturtleneck.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpsuit/whiteturtleneck.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpsuit/whiteturtleneck.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/Uniforms/Jumpsuit/whiteturtleneck.rsi/meta.json
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 4 - Низкий, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Предложение

#118 LSR-39 Queen Blade
  Resources/Locale/ru-RU/ganimed/entities/guns/lsr.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Ganimed/Entities/Objects/Weapons/Guns/Battery/lsr.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
  Resources/Prototypes/Research/arsenal.yml
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/base.png
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/equipped-BACKPACK.png
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/icon.png
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/inhand-left.png
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/inhand-right.png
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/mag-unshaded-1.png
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/mag-unshaded-2.png
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/mag-unshaded-3.png
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/mag-unshaded-4.png
  Resources/Textures/Ganimed/Objects/Guns/Battery/lsr.rsi/meta.json
  Resources/Textures/Ganimed/Objects/Guns/Projectiles/sniper.rsi/meta.json
  Resources/Textures/Ganimed/Objects/Guns/Projectiles/sniper.rsi/sniperbolt.png
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 3 - Средний, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Предложение

#117 Тяжелый скафандр ТСФ
  Resources/Locale/ru-RU/ganimed/entities/clothing/tsf_clothing.ftl
  Resources/Prototypes/Ganimed/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/Ganimed/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfheavy.rsi/icon-flash.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfheavy.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfheavy.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfheavy.rsi/off-equipped-HELMET.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfheavy.rsi/off-inhand-left.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfheavy.rsi/off-inhand-right.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfheavy.rsi/on-equipped-HELMET.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfheavy.rsi/on-inhand-left.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfheavy.rsi/on-inhand-right.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfheavy.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfheavy.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfheavy.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfheavy.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfheavy.rsi/meta.json
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 4 - Низкий, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Предложение

#121 Флаги государств
  Resources/Locale/ru-RU/ganimed/entities/misc/flags.ftl
  Resources/Prototypes/Entities/Objects/Misc/handy_flags.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/Signs/flags.yml
  Resources/Textures/Ganimed/Structures/Wallmounts/flags.rsi/elz.png
  Resources/Textures/Ganimed/Structures/Wallmounts/flags.rsi/meta.json
  Resources/Textures/Ganimed/Structures/Wallmounts/flags.rsi/tsf.png
  Resources/Textures/Ganimed/Structures/Wallmounts/flags.rsi/ussp.png
  Resources/Textures/Objects/Misc/Handy_Flags/Elz_handy_flag.rsi/icon.png
  Resources/Textures/Objects/Misc/Handy_Flags/Elz_handy_flag.rsi/inhand-left.png
  Resources/Textures/Objects/Misc/Handy_Flags/Elz_handy_flag.rsi/inhand-right.png
  Resources/Textures/Objects/Misc/Handy_Flags/Elz_handy_flag.rsi/meta.json
  Resources/Textures/Objects/Misc/Handy_Flags/TSF_handy_flag.rsi/icon.png
  Resources/Textures/Objects/Misc/Handy_Flags/TSF_handy_flag.rsi/inhand-left.png
  Resources/Textures/Objects/Misc/Handy_Flags/TSF_handy_flag.rsi/inhand-right.png
  Resources/Textures/Objects/Misc/Handy_Flags/TSF_handy_flag.rsi/meta.json
  Resources/Textures/Objects/Misc/Handy_Flags/USSP_handy_flag.rsi/icon.png
  Resources/Textures/Objects/Misc/Handy_Flags/USSP_handy_flag.rsi/inhand-left.png
  Resources/Textures/Objects/Misc/Handy_Flags/USSP_handy_flag.rsi/inhand-right.png
  Resources/Textures/Objects/Misc/Handy_Flags/USSP_handy_flag.rsi/meta.json
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 5 - На будущее, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Предложение

#126 Скреллы
  Resources/Locale/ru-RU/markings/skrells.ftl
  Resources/Locale/ru-RU/species/species.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/body/organs/skrell.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/body/parts/skrell.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/skrell.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/skrell.ftl
  Resources/Prototypes/Body/Organs/skrell.yml
  Resources/Prototypes/Body/Parts/skrell.yml
  Resources/Prototypes/Body/Prototypes/skrell.yml
  Resources/Prototypes/Chemistry/metabolizer_types.yml
  Resources/Prototypes/Damage/modifier_sets.yml
  Resources/Prototypes/Datasets/Names/skrell.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/gauze.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/skrell.yml
  Resources/Prototypes/Entities/Mobs/Player/skrell.yml
  Resources/Prototypes/Entities/Mobs/Species/skrell.yml
  Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml
  Resources/Prototypes/Species/skrell.yml
  Resources/Textures/Mobs/Customization/eyes.rsi/meta.json
  Resources/Textures/Mobs/Customization/eyes.rsi/skrell.png
  Resources/Textures/Mobs/Customization/skrell_hair.rsi/long.png
  Resources/Textures/Mobs/Customization/skrell_hair.rsi/meta.json
  Resources/Textures/Mobs/Customization/skrell_hair.rsi/short.png
  Resources/Textures/Mobs/Customization/skrell_hair.rsi/very_short.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/full.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/head_f.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/head_m.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/l_arm.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/l_foot.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/l_hand.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/l_leg.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/meta.json
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/r_arm.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/r_foot.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/r_hand.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/r_leg.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/torso_f.png
  Resources/Textures/Mobs/Species/Skrell/parts.rsi/torso_m.png
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 2 - Высокий, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Предложение

#124 Фикс гарнитур спец отрядов
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Textures/Clothing/Ears/Headsets/deathsquad.rsi/icon.png
Labels: Изменено: Спрайты, Приоритет: 2 - Высокий, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Баг
