Repository ss14-ganimed/ENT14-Master, pull requests merged in 2024-04, with the labels that each got.

#132 Airlock sound replace
  Resources/Audio/Machines/airlock_close.ogg
  Resources/Audio/Machines/airlock_open.ogg
Labels: Изменено: Звуки, Приоритет: 3 - Средний, Размер: Малый, Статус: Нуждается в рассмотрении, Сложность: 0-3 (Низкая)

#134 Новые цели станции
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Prototypes/Objectives/goals.yml
Labels: Изменено: Переводы, Приоритет: 2 - Высокий, Размер: Малый

#137 Продвинутые визоры
  Resources/Locale/ru-RU/ganimed/entities/clothing/HUDsunglusses.ftl
  Resources/Locale/ru-RU/research/technologies.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Ganimed/Entities/Clothing/Eyes/glasses.yml
  Resources/Prototypes/Recipes/Lathes/devices.yml
  Resources/Prototypes/Research/industrial.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Textures/Ganimed/Clothing/Eyes/medmeson.rsi/equipped-EYES.png
  Resources/Textures/Ganimed/Clothing/Eyes/medmeson.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Eyes/medmeson.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/Eyes/medmeson.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/Eyes/medmeson.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Eyes/medsunglasses.rsi/equipped-EYES-hamster.png
  Resources/Textures/Ganimed/Clothing/Eyes/medsunglasses.rsi/equipped-EYES.png
  Resources/Textures/Ganimed/Clothing/Eyes/medsunglasses.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Eyes/medsunglasses.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/Eyes/medsunglasses.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/Eyes/medsunglasses.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Eyes/mesonsunglasses.rsi/equipped-EYES-hamster.png
  Resources/Textures/Ganimed/Clothing/Eyes/mesonsunglasses.rsi/equipped-EYES.png
  Resources/Textures/Ganimed/Clothing/Eyes/mesonsunglasses.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Eyes/mesonsunglasses.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/Eyes/mesonsunglasses.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/Eyes/mesonsunglasses.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Eyes/scimeson.rsi/equipped-EYES.png
  Resources/Textures/Ganimed/Clothing/Eyes/scimeson.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Eyes/scimeson.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/Eyes/scimeson.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/Eyes/scimeson.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Eyes/scisunglasses.rsi/equipped-EYES-hamster.png
  Resources/Textures/Ganimed/Clothing/Eyes/scisunglasses.rsi/equipped-EYES.png
  Resources/Textures/Ganimed/Clothing/Eyes/scisunglasses.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Eyes/scisunglasses.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/Eyes/scisunglasses.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/Eyes/scisunglasses.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Eyes/supermeson.rsi/equipped-EYES.png
  Resources/Textures/Ganimed/Clothing/Eyes/supermeson.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Eyes/supermeson.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/Eyes/supermeson.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/Eyes/supermeson.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Eyes/traymeson.rsi/equipped-EYES.png
  Resources/Textures/Ganimed/Clothing/Eyes/traymeson.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Eyes/traymeson.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/Eyes/traymeson.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/Eyes/traymeson.rsi/meta.json
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 2 - Высокий, Размер: Малый, Статус: Нуждается в рассмотрении

#139 Хотфикс апстрима
  Resources/Locale/ru-RU/lathe/ui/lathe-menu.ftl
Labels: Изменено: Переводы, Статус: Нуждается в рассмотрении, Тип: Баг

#140 Фикс очков
  Resources/Prototypes/Ganimed/Catalog/Loadout/Eyes/glasses.yml
  Resources/Prototypes/Ganimed/Entities/Clothing/Eyes/glasses.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/blueshield.yml
Labels: Приоритет: 1 - Неотложный, Статус: Нуждается в рассмотрении, Тип: Критическая ошибка

#141 Окончательный фикс апстрима
  Content.Server/Shuttles/Components/StationCentcommComponent.cs
  Resources/Maps/Ganimed/centcom.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/access.yml
Labels: C#, Приоритет: 1 - Неотложный, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Критическая ошибка

#143 Добавление оставшихся ручек, сделанных Кисс
  Resources/Locale/ru-RU/ss14-ru/prototypes/ganimed/entities/objects/misc/pens.ftl
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Ganimed/Entities/Objects/Misc/pens.yml
  Resources/Textures/Ganimed/Objects/pens.rsi/bar_pen.png
  Resources/Textures/Ganimed/Objects/pens.rsi/cargo2.png
  Resources/Textures/Ganimed/Objects/pens.rsi/engineering2.png
  Resources/Textures/Ganimed/Objects/pens.rsi/medical4.png
  Resources/Textures/Ganimed/Objects/pens.rsi/meta.json
Labels: Изменено: Переводы, Изменено: Спрайты, Приоритет: 4 - Низкий, Размер: Малый, Статус: Нуждается в рассмотрении

#142 Мелкие правки
  Content.Server/Corvax/HiddenDescription/HiddenDescriptionComponent.cs
  Content.Server/Corvax/HiddenDescription/HiddenDescriptionSystem.cs
  Resources/Locale/ru-RU/corvax/hidden-description/hiddenDescription.ftl
  Resources/Locale/ru-RU/ganimed/entities/clothing/tsf_clothing.ftl
  Resources/Prototypes/Entities/Clothing/Shoes/specific.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/guardian_activators.yml
  Resources/Prototypes/Entities/Objects/Fun/darts.yml
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/Entities/Objects/Misc/implanters.yml
  Resources/Prototypes/Entities/Objects/Power/powersink.yml
  Resources/Prototypes/Entities/Objects/Shields/shields.yml
  Resources/Prototypes/Entities/Objects/Specific/Chapel/bibles.yml
  Resources/Prototypes/Entities/Objects/Specific/Hydroponics/seeds.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
  Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
  Resources/Prototypes/Entities/Objects/Tools/emag.yml
  Resources/Prototypes/Entities/Objects/Weapons/Bombs/pen.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
  Resources/Prototypes/Ganimed/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/Ganimed/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Species/human.yml
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfwhite.rsi/icon-flash.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfwhite.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfwhite.rsi/meta.json
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfwhite.rsi/off-equipped-HELMET.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfwhite.rsi/off-inhand-left.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfwhite.rsi/off-inhand-right.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfwhite.rsi/on-equipped-HELMET.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfwhite.rsi/on-inhand-left.png
  Resources/Textures/Ganimed/Clothing/Head/Hardsuits/tsfwhite.rsi/on-inhand-right.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfwhite.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfwhite.rsi/icon.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfwhite.rsi/inhand-left.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfwhite.rsi/inhand-right.png
  Resources/Textures/Ganimed/Clothing/OuterClothing/Hardsuits/tsfwhite.rsi/meta.json
Labels: C#, Изменено: Переводы, Изменено: Спрайты, Приоритет: 2 - Высокий, Размер: Малый, Статус: Нуждается в рассмотрении, Тип: Баг
